import type { Metadata } from "next";
import { Rubik, Manrope } from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rubik = Rubik({
  subsets: ['latin'], // required
  variable: '--font-rubik', // optional (for CSS vars)
})

const maprope = Manrope({
  subsets: ['latin'], // required
  variable: '--font-manrope', // optional (for CSS vars)
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {children}
      </body>
    </html>
  );
}
